### ISSUE TITLE
NgGenericPipe doesn't support Pipes that are typescript type guards for classes

### ISSUE THREAD

**Issue by L3444** [nigrosimone/ng-generic-pipe#1]
Hello,

thank you for this library, it's very nice for reducing boilerplate code. There's just a very specific issue I'm having with replacing some of my pipes:

the following example with a normal angular pipe works, the compiler understands that the pipe is a type guard, therefore `{{ object.value }}` in the template works:

```ts
import { ChangeDetectionStrategy, Component, Pipe, PipeTransform } from "@angular/core";
import { CommonModule } from "@angular/common";

class MyClass {
  constructor(public value: string = '') {}
}

@Pipe({
  name: "isMyClass",
  standalone: true,
})
export class IsMyClassPipe implements PipeTransform {
  transform(obj: unknown): obj is MyClass {
    return obj instanceof MyClass;
  }
}

@Component({
  selector: "app-examples",
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [CommonModule, IsMyClassPipe],
  template: `
    <ng-container *ngIf="object | isMyClass">
      value: {{ object.value }}
    </ng-container>
  `,
})
export class ExamplesComponent {
  protected object: unknown = new MyClass('Lorem Ipsum'); // the ": unknown" is important, without it the template already knows that it's of type MyClass and the type guard isn't needed
}
```

When you try to write the same code with ngGenericPipe it sadly doesn't work:
NOTE: this is only an issue with classes, the same code works if MyClass were a type/interface instead of a class:

```ts
import { ChangeDetectionStrategy, Component } from "@angular/core";
import { CommonModule } from "@angular/common";
import { NgGenericPipeModule } from "ng-generic-pipe";

class MyClass {
  constructor(public value: string = '') {}
}

@Component({
  selector: "app-examples",
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [CommonModule, NgGenericPipeModule],
  template: `
    <ng-container *ngIf="object | ngGenericPipe: isMyClass">
      value: {{ object.value }}
    </ng-container>
  `,
})
export class ExamplesComponent {
  protected object: unknown = new MyClass('Lorem Ipsum'); // the ": unknown" is important, without it the template already knows that it's of type MyClass and the type guard isn't needed

  isMyClass(obj: unknown): obj is MyClass {
    return obj instanceof MyClass;
  }
}
```

This results in a compiler error in line `value: {{ object.value }}`:
```
examples.component.ts:16:24 - error TS2571: Object is of type 'unknown'.
```

In my use case, the object can be one of multiple different classes, so simply casting it with ng-as isn't an option.

Angular Version: 15.0.3
ng-generic-pipe Version: 15.0.1

**Comment by nigrosimone** [comment]
Hi, I have made another library https://github.com/nigrosimone/ng-as "Angular pipe and directive for type casting template variables.". Maybe, it solve your issue, take a loock.

**Comment by L3444** [comment]
@nigrosimone In my use case, the object can be one of multiple different classes, so simply casting it with ng-as isn't an option.

**Comment by L3444** [comment]
Hello @nigrosimone,

casting it would work, yes. It's not optimal because it re-adds some boilerplate code and requires another dependency, but it's a decent workaround:
```ts
<ng-container *ngIf="(object | ngGenericPipe: isMyClass) && (object | as: myClass) as object">
  value: {{ object.value }}
  value: {{ object.value }}
</ng-container>

...

protected myClass?: MyClass;
```
